{"results":[{"instructorExitCode":0,"studentExitCode":0,"studentErrOut":"","instructorStdOut":"LessThan\n","instructorExeTime":23,"studentStdOut":"LessThan\n","studentExeTime":3,"instructorErrOut":""},{"instructorExitCode":0,"studentExitCode":139,"studentErrOut":"Seg fault","instructorStdOut":"Inbetween boundaries\n","instructorExeTime":3,"studentStdOut":"","studentExeTime":3,"instructorErrOut":""},{"instructorExitCode":0,"studentExitCode":139,"studentErrOut":"Seg fault","instructorStdOut":"Inbetween boundaries\n","instructorExeTime":2,"studentStdOut":"","studentExeTime":3,"instructorErrOut":""},{"instructorExitCode":0,"studentExitCode":0,"studentErrOut":"","instructorStdOut":"6\n","instructorExeTime":79,"studentStdOut":"6\n","studentExeTime":73,"instructorErrOut":""},{"instructorExitCode":0,"studentExitCode":1,"studentErrOut":"Exception in thread \"main\" java.lang.NumberFormatException: For input string: \"4\" under radix 2\n\tat java.base\/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)\n\tat java.base\/java.lang.Long.parseLong(Long.java:711)\n\tat Main.main(Main.java:4)\n","instructorStdOut":"Invalid value\n","instructorExeTime":53,"studentStdOut":"","studentExeTime":45,"instructorErrOut":""},{"instructorExitCode":0,"studentExitCode":0,"studentErrOut":"Stream closed","instructorStdOut":"Finished Loop\n","instructorExeTime":74,"studentStdOut":"","studentExeTime":5007,"instructorErrOut":""},{"instructorExitCode":0,"studentExitCode":0,"studentErrOut":"","instructorStdOut":"","instructorExeTime":91,"studentStdOut":"","studentExeTime":111,"instructorErrOut":""},{"instructorExitCode":0,"studentExitCode":0,"studentErrOut":"","instructorStdOut":"truefalsetruefalsetruefalsetruefalsetruefalsefalsefalsetruefalsetruefalsetruefalsetruefalse\n","instructorExeTime":85,"studentStdOut":"truefalsetruefalsetruefalsetruefalsetruefalsefalsefalsetruefalsetruefalsetruefalsetruefalse\n","studentExeTime":107,"instructorErrOut":""},{"instructorExitCode":0,"studentExitCode":0,"studentErrOut":"Exception in thread \"Thread-1\" Exception in thread \"Thread-0\" java.lang.AssertionError: RaceCondition occurred\n\tat Number.run(Module9.java:36)\njava.lang.AssertionError: RaceCondition occurred\n\tat Number.run(Module9.java:36)\n","instructorStdOut":"","instructorExeTime":46,"studentStdOut":"","studentExeTime":50,"instructorErrOut":""},{"instructorExitCode":0,"studentExitCode":0,"studentErrOut":"","instructorStdOut":"0\n1\nThread with Priority 0 executed\n2\nThread with Priority 1 executed\n3\nThread with Priority 2 executed\n4\nThread with Priority 3 executed\n5\nThread with Priority 4 executed\n6\nThread with Priority 5 executed\n7\nThread with Priority 6 executed\n8\nThread with Priority 7 executed\n9\nThread with Priority 8 executed\n10\nThread with Priority 9 executed\n0\n1\n2\n3\n","instructorExeTime":80,"studentStdOut":"0\n0\n1\nThread with Priority 0 executed\n0\n1\n2\nThread with Priority 1 executed\n0\n1\n2\n3\nThread with Priority 2 executed\n0\n1\n2\n3\nThread with Priority 3 executed\n","studentExeTime":84,"instructorErrOut":""}]}